language: go
go:
  - 1.13
  - 1.12
os:
  - linux
  - osx
  - windows
before_install:
- go get github.com/onsi/ginkgo/...
- go get github.com/onsi/gomega/...
- go install github.com/onsi/ginkgo/ginkgo
script: PATH=$PATH:$HOME/gopath/bin ginkgo -r .
branches:
  only:
  - master
